#!/bin/bash

shopt -s globstar

div() {
    local ret=$((100 * $1 / $2))
    printf "%6g.%02g" ${ret:0:${#ret}-2} ${ret:${#ret}-2:2}
}

(
echo $'ID\tNAME\tIP\t MEMORY'
docker ps --no-trunc --format '{{.ID}}:{{.Names}}' |
    while IFS=: read id name; do
        ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' $id)
        mem=$(cat /sys/fs/cgroup/memory/**/*-$id/memory.usage_in_bytes 2>/dev/null)
        if ((mem > 536870912))
        then
            mem=$(div $mem 1073741824)
            sfx=G
        elif ((mem > 524288))
        then
            mem=$(div $mem 1048576)
            sfx=M
        elif ((mem > 512))
        then
            mem=$(div $mem 1024)
            sfx=k
        else
            mem=$(div $mem 1)
            sfx=""
        fi
        printf "%12s\t%s\t\t%s\t%6s%s\n" "${id:0:12}" "$name" "${ip:-N/A}" "${mem:-N/A}" "$sfx"
    done
    ) | column -s $'\t' -t
